apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: group-service
  labels: 
    app: group-service
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: group-service
  template: 
    metadata: 
      labels: 
        app: group-service
    spec: 
      containers: 
      - name: group-service
        image: vsacre/groupservice
        ports: 
        - containerPort: 3000
