apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: authentication-service
  labels: 
    app: authentication-service
spec: 
  replicas: 1
  selector: 
    matchLabels:
      app: authentication-service
  template: 
    metadata:
      labels: 
        app: authentication-service
    spec:
      containers: 
      - name: authentication-service
        image: vsacre/authenticationservice
        ports: 
        - containerPort: 3000
        env:
        - name: ACTIVATION_LINK
          value: http://35.242.206.155/authentication/api/activate
